import React from 'react'
import Login from './page'


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

const layout = () => {
  return (
    <div>
        <Login />
    </div>
  )
}

export default layout